/**:
  ros__parameters:
    # Long: Timeout for each service to be detected as available in milliseconds
    # Units: milliseconds
    service_timeout_ms : 200

    # Long: Timeout for each service call in milliseconds
    # Units: milliseconds
    call_timeout_ms : 1000

    # String: The namespace for nodes in this subsystem. All nodes under this namespace will have their lifecycle's managed by this controller
    subsystem_namespace: /hardware_interface

    # Required subsystem controller nodes for the overall system to be functional and will have their lifecycle's managed
    # TODO Move this parameter to carma config in some capacity
    required_subsystem_nodes: ['']

    # List of nodes which will not be directly managed by this subsystem controller 
    # but which are required to be operational for the subsystem to function
    unmanaged_required_nodes: ['']

    # List of nodes in the namespace which will not be managed by this subsystem controller
    # Specifically includes the lidar and gps nodes which are handled in other subsystem controllers
    unmanaged_namespace_nodes : ['']
    
    # Boolean: If this flag is true then all nodes under subsystem_namespace are treated as required in addition to any nodes in required_subsystem_nodes
    full_subsystem_required: false

    # Double: The time allocated for system startup in seconds
    startup_duration: 30.0

    # Double: The timeout threshold for essential drivers in ms
    required_driver_timeout: 3000.0